language: cpp

compiler:
  - gcc

script:
  - cd projects/cmake
  - ./build.sh
  - rb

# safelist
branches:
  only:
  - master
  - development
  
# notifications
notifications:
  slack:
    on_success: change
