language: cpp

compiler:
  - gcc

script:
  - cd projects/cmake
  - ./build.sh
  - echo "\"Hello World\"" | ./rb

# safelist
branches:
  only:
  - master
  - development
  
# notifications
notifications:
  slack: revbayes:bQO6VTun0Orhx2NiKktVPDsS
